/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _MINIFYJPEG_H_RPCGEN
#define _MINIFYJPEG_H_RPCGEN

#include <rpc/rpc.h>

#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif


struct Img {
	struct {
		u_int buf_len;
		char *buf_val;
	} buf;
};
typedef struct Img Img;

#define MINIFY_PROG 0x23451111
#define MINIFY_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define MINIFYJPEG 1
extern  enum clnt_stat minifyjpeg_1(Img , Img *, CLIENT *);
extern  bool_t minifyjpeg_1_svc(Img , Img *, struct svc_req *);
extern int minify_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define MINIFYJPEG 1
extern  enum clnt_stat minifyjpeg_1();
extern  bool_t minifyjpeg_1_svc();
extern int minify_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Img (XDR *, Img*);

#else /* K&R C */
extern bool_t xdr_Img ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_MINIFYJPEG_H_RPCGEN */
