/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "stringops.h"


void
stringops_prog_1(char *host)
{
	CLIENT *clnt;
	String  *result_1;
	String upper_1_arg1;

#ifndef	DEBUG
	clnt = clnt_create (host, STRINGOPS_PROG, STRINGOPS_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = upper_1(upper_1_arg1, clnt);
	if (result_1 == (String *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	stringops_prog_1 (host);
exit (0);
}
