/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "stringops.h"

String *
upper_1_svc(String arg1,  struct svc_req *rqstp)
{
	static String  result;

	/*
	 * insert server code here
	 */

	return &result;
}
