/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "stringops.h"

bool_t
xdr_String (XDR *xdrs, String *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->str, 20))
		 return FALSE;
	return TRUE;
}
