/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "add.h"

int *
add_1_svc(IntPair *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
	// printf("add function called!\n");
	 result = argp->a + argp->b;

	 printf("Parameters: %d, %d, Result = %d\n", argp->a, argp->b, result);

	return &result;
}
