/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _STRINGOPS_H_RPCGEN
#define _STRINGOPS_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct String {
	char *str;
};
typedef struct String String;

#define STRINGOPS_PROG 0x20000001
#define STRINGOPS_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define UPPER 1
extern  String * upper_1(String , CLIENT *);
extern  String * upper_1_svc(String , struct svc_req *);
extern int stringops_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define UPPER 1
extern  String * upper_1();
extern  String * upper_1_svc();
extern int stringops_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_String (XDR *, String*);

#else /* K&R C */
extern bool_t xdr_String ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_STRINGOPS_H_RPCGEN */
